title: "Adam Simpson Portfolio"
description: "Data Science & SWE Projects"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Simple Navbar
navigation:
  - title: "Adam Simpson"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects/"

author: "Adam Simpson"
url: "https://will51mps0n.github.io/will51mps0n"
