title: "Adam Simpson Portfolio"
description: "Data Science & Analytics Projects by Adam Simpson"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Optional: Custom Logo (put logo.png in assets/images/)
# logo: /assets/images/logo.png

# Optional: Social links
social_links:
  - name: GitHub
    url: https://github.com/will51mps0n
  - name: LinkedIn
    url: https://linkedin.com/in/your-linkedin

# Custom colors (Cayman supports these!)
color_scheme: "dark"

# Navbar Links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects/"

# SEO tags
author: "Adam Simpson"
url: "https://will51mps0n.github.io/will51mps0n"
